export function useServices() {}
export function useService() {}
export function useCreateService() {}
export function useUpdateService() {}
export function useDeleteService() {}
export function useServiceState() {}
export function useServiceReplicaScaling() {}
export function useServicePassword() {}
export function useServicePrivateEndpointConfig() {}
export function useServiceQueryEndpoint() {}
export function useServicePrometheus() {}
